version: '3.8'

services:
  postgres-auth:
    image: postgres:15-alpine
    container_name: eco-postgres-auth
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_auth:/var/lib/postgresql/data

  postgres-catalog:
    image: pgvector/pgvector:pg16
    container_name: postgres-catalog
    restart: always
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password
      POSTGRES_DB: catalog_db
    ports:
      - '5433:5432'
    volumes:
      - catalog_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: eco-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata_auth:
  catalog_data:
